// Plugin
export { createM3UI } from './plugin'
export type { M3UIOptions } from './plugin'

// Composables
export { useTheme } from './composables/useTheme'
export type { Theme } from './composables/useTheme'
export { useColorPalette, palettes } from './composables/useColorPalette'
export type { Palette } from './composables/useColorPalette'
export { useToast } from './composables/useToast'
export type { Toast, ToastVariant, ToastPosition, ToastAction, ToastOptions } from './composables/useToast'
export { useFieldBg } from './composables/useFieldBg'
export { useLocale, defaultLocale } from './composables/useLocale'
export type { M3Locale } from './composables/useLocale'
export { useDevice } from './composables/useDevice'
export { useNotification } from './composables/useNotification'
export type { Notification, NotificationVariant, NotificationPosition, NotificationOptions } from './composables/useNotification'
export { useDebounce } from './composables/useDebounce'

// Components
export { default as MAbsolute } from './components/MAbsolute.vue'
export { default as MAlert } from './components/MAlert.vue'
export { default as MAutocomplete } from './components/MAutocomplete.vue'
export { default as MAppBar } from './components/MAppBar.vue'
export { default as MAppLayout } from './components/MAppLayout.vue'
export { default as MAspectRatio } from './components/MAspectRatio.vue'
export { default as MAvatar } from './components/MAvatar.vue'
export { default as MBadge } from './components/MBadge.vue'
export { default as MBottomSheet } from './components/MBottomSheet.vue'
export { default as MBox } from './components/MBox.vue'
export { default as MBreadcrumbs } from './components/MBreadcrumbs.vue'
export { default as MButton } from './components/MButton.vue'
export { default as MButtonGroup } from './components/MButtonGroup.vue'
export type { ButtonGroupOption } from './components/MButtonGroup.vue'
export { default as MCalendar } from './components/MCalendar.vue'
export { default as MCard } from './components/MCard.vue'
export { default as MCarousel } from './components/MCarousel.vue'
export { default as MCenter } from './components/MCenter.vue'
// MChart — import from '@m3ui-vue/m3ui-vue/chart'
export { default as MChatBubble } from './components/MChatBubble.vue'
export { default as MCheckbox } from './components/MCheckbox.vue'
export { default as MChip } from './components/MChip.vue'
// MCodeEditor — import from '@m3ui-vue/m3ui-vue/code-editor'
export { default as MColorPicker } from './components/MColorPicker.vue'
export { default as MColorPickerModal } from './components/MColorPickerModal.vue'
export { default as MCommandPalette } from './components/MCommandPalette.vue'
export { default as MConfirmDialog } from './components/MConfirmDialog.vue'
export { default as MContainer } from './components/MContainer.vue'
export { default as MContextMenu } from './components/MContextMenu.vue'
export { default as MDataTable } from './components/MDataTable.vue'
export { default as MDatePicker } from './components/MDatePicker.vue'
export { default as MDatePickerModal } from './components/MDatePickerModal.vue'
export { default as MDateRangePicker } from './components/MDateRangePicker.vue'
export { default as MDateRangePickerModal } from './components/MDateRangePickerModal.vue'
export { default as MDialog } from './components/MDialog.vue'
export { default as MDivider } from './components/MDivider.vue'
export { default as MDragDropList } from './components/MDragDropList.vue'
export { default as MEmoji } from './components/MEmoji.vue'
export { default as MEmojiButton } from './components/MEmojiButton.vue'
export { default as MEmojiSelector } from './components/MEmojiSelector.vue'
export { default as MEmptyState } from './components/MEmptyState.vue'
export { default as MExpansionPanel } from './components/MExpansionPanel.vue'
export { default as MFab } from './components/MFab.vue'
export { default as MFileUpload } from './components/MFileUpload.vue'
export { default as MFixed } from './components/MFixed.vue'
export { default as MFooter } from './components/MFooter.vue'
export { default as MFlex } from './components/MFlex.vue'
export { default as MFullscreen } from './components/MFullscreen.vue'
export { default as MGrid } from './components/MGrid.vue'
export { default as MHotkeys } from './components/MHotkeys.vue'
export { default as MIcon } from './components/MIcon.vue'
export { default as MIconButton } from './components/MIconButton.vue'
export { default as MInfiniteScroll } from './components/MInfiniteScroll.vue'
// MJsonEditor — import from '@m3ui-vue/m3ui-vue/code-editor'
export { default as MJsonViewer } from './components/MJsonViewer.vue'
export { default as MKanban } from './components/MKanban.vue'
export { default as MList } from './components/MList.vue'
export { default as MListItem } from './components/MListItem.vue'
export { default as MListSubheader } from './components/MListSubheader.vue'
export { default as MLoadingOverlay } from './components/MLoadingOverlay.vue'
// MMarkdown — import from '@m3ui-vue/m3ui-vue/markdown'
export { default as MMasonry } from './components/MMasonry.vue'
export { default as MMenu } from './components/MMenu.vue'
export { default as MMenuItem } from './components/MMenuItem.vue'
export { default as MMaskField } from './components/MMaskField.vue'
export type { MaskPreset } from './components/MMaskField.vue'
export { default as MMultiAutocomplete } from './components/MMultiAutocomplete.vue'
export { default as MMultiSelect } from './components/MMultiSelect.vue'
export type { MultiSelectOption } from './components/MMultiSelect.vue'
export { default as MNavigationBar } from './components/MNavigationBar.vue'
export { default as MNumberField } from './components/MNumberField.vue'
export { default as MNavigationDrawer } from './components/MNavigationDrawer.vue'
export { default as MNavigationRail } from './components/MNavigationRail.vue'
export { default as MOverlay } from './components/MOverlay.vue'
export { default as MPagination } from './components/MPagination.vue'
export { default as MProgressBar } from './components/MProgressBar.vue'
export { default as MCircleProgressBar } from './components/MCircleProgressBar.vue'
export { default as MRadio } from './components/MRadio.vue'
export { default as MRadioGroup } from './components/MRadioGroup.vue'
export { default as MRating } from './components/MRating.vue'
export { default as MRelative } from './components/MRelative.vue'
export { default as MResponsive } from './components/MResponsive.vue'
export { default as MResult } from './components/MResult.vue'
// MRichTextEditor — import from '@m3ui-vue/m3ui-vue/rich-text-editor'
export { default as MScheduler } from './components/MScheduler.vue'
export { default as MScrollable } from './components/MScrollable.vue'
export { default as MSection } from './components/MSection.vue'
export { default as MSegmentedButton } from './components/MSegmentedButton.vue'
export { default as MSelect } from './components/MSelect.vue'
export type { SelectOption } from './components/MSelect.vue'
export { default as MSideSheet } from './components/MSideSheet.vue'
export { default as MSkeleton } from './components/MSkeleton.vue'
export { default as MSlider } from './components/MSlider.vue'
export { default as MSnackbar } from './components/MSnackbar.vue'
export { default as MSpacer } from './components/MSpacer.vue'
export { default as MSpinner } from './components/MSpinner.vue'
export { default as MSplitButton } from './components/MSplitButton.vue'
export type { SplitButtonItem } from './components/MSplitButton.vue'
export { default as MSplitter } from './components/MSplitter.vue'
export { default as MSpotlightSearch } from './components/MSpotlightSearch.vue'
export { default as MStack } from './components/MStack.vue'
export { default as MStatCard } from './components/MStatCard.vue'
export { default as MStepper } from './components/MStepper.vue'
export { default as MSticky } from './components/MSticky.vue'
export { default as MSubtitle } from './components/MSubtitle.vue'
export { default as MSwitch } from './components/MSwitch.vue'
export { default as MTable } from './components/MTable.vue'
export { default as MTagInput } from './components/MTagInput.vue'
export { default as MTabs } from './components/MTabs.vue'
// MTerminal — import from '@m3ui-vue/m3ui-vue/terminal'
export { default as MText } from './components/MText.vue'
export { default as MTextField } from './components/MTextField.vue'
export { default as MTimeline } from './components/MTimeline.vue'
export { default as MTimePicker } from './components/MTimePicker.vue'
export { default as MTimePickerModal } from './components/MTimePickerModal.vue'
export { default as MTitle } from './components/MTitle.vue'
export { default as MTooltip } from './components/MTooltip.vue'
export { default as MToolbar } from './components/MToolbar.vue'
export { default as MTopAppBar } from './components/MTopAppBar.vue'
export { default as MTour } from './components/MTour.vue'
export { default as MTransferList } from './components/MTransferList.vue'
export { default as MTree } from './components/MTree.vue'
export { default as MTreeTable } from './components/MTreeTable.vue'
export { default as MVirtualTable } from './components/MVirtualTable.vue'
export { default as MWindow } from './components/MWindow.vue'

// Re-export types from components that define them
export type { EmojiCategory } from './data/emojis'
export { emojiCategories, allEmojis, randomEmoji } from './data/emojis'
export type { Placement } from './components/MAbsolute.vue'
export type { BadgePosition, BadgeOverlap } from './components/MBadge.vue'
export type { CalendarEvent } from './components/MCalendar.vue'
export type { CarouselItem } from './components/MCarousel.vue'
export type { ContextMenuItem } from './components/MContextMenu.vue'
export type { DataTableColumn, DataTableFetchParams } from './components/MDataTable.vue'
export type { DateRange } from './components/MDateRangePicker.vue'
export type { DragDropItem } from './components/MDragDropList.vue'
export type { UploadFile } from './components/MFileUpload.vue'
export type { HotkeyBinding } from './components/MHotkeys.vue'
export type { KanbanColumn, KanbanCard } from './components/MKanban.vue'
export type { NavBarItem } from './components/MNavigationBar.vue'
export type { DrawerItem, DrawerSection } from './components/MNavigationDrawer.vue'
export type { SpeedDialItem } from './components/MFab.vue'
export type { NavRailItem } from './components/MNavigationRail.vue'
export type { SchedulerEvent } from './components/MScheduler.vue'
export type { SegmentedOption } from './components/MSegmentedButton.vue'
export type { SpotlightResult } from './components/MSpotlightSearch.vue'
export type { StepItem } from './components/MStepper.vue'
export type { CommandItem } from './components/MCommandPalette.vue'
export type { TableFetchParams } from './components/MTable.vue'
export type { TimelineItem } from './components/MTimeline.vue'
export type { TourStep } from './components/MTour.vue'
export type { TransferItem } from './components/MTransferList.vue'
export type { TreeNode } from './components/MTree.vue'
export type { TreeTableColumn, TreeTableRow } from './components/MTreeTable.vue'
export type { VTableColumn } from './components/MVirtualTable.vue'
export type { BreadcrumbItem } from './components/MBreadcrumbs.vue'
export type { TextVariant } from './components/MText.vue'
export type { ListItemLeading, ListItemTrailing } from './components/MListItem.vue'
